17-computerController - Controller List View and Index/Add methods
TeamCharles/workforce-management pull request #48
Opened 2016-11-03 20:19 UTC by matthamil

## Status
**READY**

## Documentation

[**X**] I have fully documented features in this PR's code. Please put an `X` in the box to confirm.

[ ] This PR does **NOT** require documentation.

## Description
Users can now view `localhost:5000/computer` to view a list of all computers and their assigned employees. The `Add` a computer button **does not work** because there is not a view yet for that method.

## Resolves Issue Number

https://github.com/TeamCharles/workforce-management/issues/17

https://github.com/TeamCharles/workforce-management/issues/16

## Deploy Notes

```sh
git pull --prune
git checkout 17-computerController
dotnet run
```

## Steps to Test or Reproduce

1. Navigate to `localhost:5000/Computer`

1. The list should include all assigned and unassigned computers.

## Impacted Files in Application

* Controllers/
* Views/
* ViewModels/Computer
* Startup.cs

2016-11-03 20:42 UTC, garrett-vangilder approved these changes

2016-11-03 20:42 UTC, garrett-vangilder commented
I should probably go back and add a default route to my branch. LGTM

2016-11-04 02:23 UTC, daynewright requested changes
I can see how splitting this up can make it difficult to test without all the parts.  Definitely shows how testing would fix this issue.

2016-11-04 02:23 UTC, daynewright commented on src/workforce-management/Controllers/ComputerController.cs
> +        [HttpPost]
Should we add the `GET` method here too for issue #17 ?

```
        [HttpGet]
        public IActionResult Add()
        {
            var model = new ComputerAdd();
            return View(model);
        }
```

2016-11-04 02:29 UTC, matthamil commented on src/workforce-management/Controllers/ComputerController.cs
> +        [HttpPost]
@daynewright Looks like I forgot to add that and only added the method that fires upon form submit. Good catch

2016-11-04 16:25 UTC, matthamil commented
@TeamCharles/team Recommended changes made, ready for review

2016-11-04 16:25 UTC, matthamil commented on src/workforce-management/Controllers/ComputerController.cs
> +        [HttpPost]
@daynewright Added

2016-11-04 16:34 UTC, MattKraatz approved these changes
LGTM with a few comments

2016-11-04 16:34 UTC, MattKraatz commented on src/workforce-management/Controllers/ComputerController.cs
> +                    assignedEmployee.Computer = newComputer;
Do we need to save the entire computer instance to the employee in the db or just the computerId?

2016-11-04 16:34 UTC, MattKraatz commented on src/workforce-management/Controllers/ComputerController.cs
> +                return RedirectToAction("Index", new RouteValueDictionary(
you can simplify this to `return RedirectToAction("Index")` since we're already in the Computer controller

2016-11-04 16:34 UTC, MattKraatz commented on src/workforce-management/Startup.cs
> +                routes.MapRoute(
I don't think we need this route stuff. It will go to Index automatically

2016-11-04 16:34 UTC, MattKraatz commented on src/workforce-management/ViewModels/Computer/ComputerAdd.cs
> +     * Class: ComputerIndex
Check your name here

2016-11-04 16:37 UTC, daynewright approved these changes

2016-11-04 16:41 UTC, matthamil commented on src/workforce-management/Controllers/ComputerController.cs
> +                    assignedEmployee.Computer = newComputer;
Good catch

2016-11-04 16:43 UTC, matthamil commented
@MattKraatz Added changes/fixes

2016-11-07 15:12 UTC, Anulfo commented
LGTM

2016-11-07 15:39 UTC, daynewright commented
LGTM

2016-11-07 15:40 UTC, merged