60-edit-training-program :: Edit training program
TeamCharles/workforce-management pull request #73
Opened 2016-11-08 21:07 UTC by daynewright

## Status
**READY**

## Documentation

[X] I have fully documented features in this PR's code. Please put an `X` in the box to confirm.

[ ] This PR does **NOT** require documentation.

## Description
Creates edit view and submits edited training program.

## Resolves Issue Number
#60 

## Deploy Notes
Notes regarding deployment the contained body of work.  These should note any
db migrations, etc.

```sh
git pull --prune
git checkout 60-edit-training-program
dotnet run
```

## Steps to Test or Reproduce
Outline the steps to test or reproduce the PR here.

1.  dotnet run
2.  navigate to training programs
3.  click on a training program
4.  click edit
5.  edit it and save
6.  enjoy

## Impacted Files in Application
List general components of the application that this PR will affect:

* TrainingProgramController.cs
* TrainingProgramEdit.cs
* Edit.cshtml

2016-11-08 21:17 UTC, matthamil requested changes
Documentation issues

2016-11-08 21:17 UTC, matthamil commented on src/workforce-management/Controllers/TrainingProgramController.cs
>           * CLASS: ProductTypes
"CLASS: ProductTypes"
🤔

2016-11-08 21:17 UTC, matthamil commented on src/workforce-management/Controllers/TrainingProgramController.cs
>           *   IActionResult Index() - Returns a View listing all Training Programs.
Missing documentation for other methods

2016-11-09 03:19 UTC, daynewright commented on src/workforce-management/Controllers/TrainingProgramController.cs
>           * CLASS: ProductTypes
What the what?!? 👀

2016-11-09 03:19 UTC, daynewright commented on src/workforce-management/Controllers/TrainingProgramController.cs
>           *   IActionResult Index() - Returns a View listing all Training Programs.
✅

2016-11-09 03:42 UTC, daynewright commented
@matthamil Documentation updated.

2016-11-09 05:59 UTC, daynewright commented
I fixed issue #74 within this pull request as well.  Be sure to check it too!  😨

2016-11-09 15:16 UTC, matthamil approved these changes

2016-11-09 15:19 UTC, matthamil commented
Works like a charm :star2:

2016-11-09 15:54 UTC, MattKraatz commented
Looks GREAT to me

2016-11-09 16:04 UTC, garrett-vangilder commented
LGTM 👍  💯

2016-11-09 16:04 UTC, garrett-vangilder commented
LGTM 👍  💯

2016-11-09 16:40 UTC, merged